// frontend/src/components/ErrorBox.tsx
import type { CourtFailure } from '@/lib/court';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Button } from '@/components/ui/button';
import { Icon } from './Icon';

const TITLES: Record<CourtFailure['kind'], string> = {
	idea: 'The court couldn’t read that idea',
	data: 'Couldn’t load the prices',
	network: 'Can’t reach the court',
	rate: 'Too many rulings for now',
	server: 'The court hit a problem',
	cut: 'The ruling was cut off'
};

export function ErrorBox({ failure, onretry }: { failure: CourtFailure; onretry: () => void }) {
	return (
		<Alert className="border-destructive/35 bg-danger-muted" role="alert">
			<Icon name="x" className="mt-0.5 size-4 text-danger-foreground" />
			<AlertTitle className="text-[13px]">{TITLES[failure.kind]}</AlertTitle>
			<AlertDescription className="text-[12.5px] text-subtle">
				{failure.message}
				<div className="mt-2 flex flex-wrap gap-2">
					<Button variant="secondary" size="sm" onClick={onretry}>
						<Icon name="retry" className="size-4" />
						Retry
					</Button>
				</div>
			</AlertDescription>
		</Alert>
	);
}

// frontend/src/lib/components/ErrorBox.svelte
<script lang="ts">
	import type { CourtFailure } from '#lib/court.svelte.js';
	import Icon from './Icon.svelte';

	interface Props {
		failure: CourtFailure;
		onretry: () => void;
		onexample: () => void;
	}

	let { failure, onretry, onexample }: Props = $props();

	const TITLES = {
		idea: 'The court couldn’t read that idea',
		data: 'Couldn’t load the prices',
		network: 'Can’t reach the court',
		rate: 'Too many rulings for now',
		server: 'The court hit a problem',
		cut: 'The ruling was cut off'
	};
</script>

<div class="flex items-start gap-3 rounded-lg border border-danger/35 bg-danger-muted px-4 py-3.5" role="alert">
	<Icon name="x" class="mt-0.5 size-5 shrink-0 text-danger-foreground" />
	<div class="grid gap-2">
		<p class="m-0 font-semibold">{TITLES[failure.kind]}</p>
		<p class="m-0 text-[13.5px] text-subtle">{failure.message}</p>
		<div class="flex flex-wrap gap-2">
			{#if failure.kind === 'idea'}
				<button type="button" class="btn btn-secondary" onclick={onexample}>Use an example idea</button>
			{:else if failure.kind !== 'rate'}
				<button type="button" class="btn btn-secondary" onclick={onretry}>
					<Icon name="retry" class="size-4" />Try again
				</button>
			{/if}
		</div>
	</div>
</div>
