// frontend/src/components/TopBar.tsx
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { useCourtSession } from '@/lib/useCourt';
import { cn } from '@/lib/utils';

function StatusBadge({ tone, live, children }: { tone: 'success' | 'warning' | 'danger' | 'neutral' | 'info'; live?: boolean; children: React.ReactNode }) {
	const cls = {
		success: 'bg-success-muted text-success-foreground',
		warning: 'bg-warning-muted text-warning-foreground',
		danger: 'bg-danger-muted text-danger-foreground',
		neutral: 'bg-muted text-subtle',
		info: 'bg-info-muted text-info-foreground'
	}[tone];
	return (
		<Badge variant="secondary" className={cn('gap-1.5', cls)}>
			<span className={cn('size-1.5 rounded-full bg-current', live && 'motion-safe:animate-pulse')} aria-hidden="true" />
			{children}
		</Badge>
	);
}

export function TopBar({ onhow }: { onhow: () => void }) {
	const session = useCourtSession();
	const market = session.result?.market;
	const source = (() => {
		if (session.error?.kind === 'data') return { tone: 'danger' as const, text: 'Bitget offline' };
		if (!market) return { tone: 'neutral' as const, text: session.running ? 'Loading' : 'Waiting' };
		if (market.source === 'bitget') return { tone: 'success' as const, text: 'Live Bitget' };
		return { tone: 'warning' as const, text: 'Saved Bitget' };
	})();

	return (
		<header className="flex flex-wrap items-center gap-3">
			<div className="min-w-0 flex-1">
				<h1 className="m-0 text-[14px] font-semibold tracking-tight">Strategy court</h1>
				<p className="m-0 text-[11px] text-muted-foreground">Fixed code rules PASS or FAIL on hourly Bitget stock-token prices.</p>
			</div>
			<div className="flex shrink-0 flex-wrap items-center justify-end gap-2 max-sm:w-full max-sm:justify-start" role="group" aria-label="Status">
				<StatusBadge tone={source.tone} live={session.running}>
					<span className="sr-only">Data: </span>
					{source.text}
				</StatusBadge>
				{session.markets && (
					<StatusBadge tone={session.markets.ai_enabled ? 'info' : 'neutral'}>
						{session.markets.ai_enabled ? `AI · ${session.markets.ai_model?.split('/').at(-1) ?? 'on'}` : 'AI off'}
					</StatusBadge>
				)}
				<Button variant="secondary" size="sm" onClick={onhow}>
					How it works
				</Button>
			</div>
		</header>
	);
}

// frontend/src/lib/components/TopBar.svelte
<script lang="ts">
	import type { CourtSession } from '#lib/court.svelte.js';
	import { toggleTheme } from '#lib/theme.js';
	import Badge from './Badge.svelte';
	import BrandMark from './BrandMark.svelte';
	import Icon from './Icon.svelte';

	let { session, onhow }: { session: CourtSession; onhow: () => void } = $props();

	const market = $derived(session.result?.market);
	const markets = $derived(session.markets);
	const source = $derived.by(() => {
		if (!market) return { tone: 'neutral' as const, text: session.running ? 'Loading' : 'Waiting' };
		if (market.source === 'bitget') return { tone: 'success' as const, text: 'Live Bitget' };
		if (market.source === 'saved') return { tone: 'warning' as const, text: 'Saved Bitget prices' };
		return { tone: 'warning' as const, text: 'Practice prices (dev mode)' };
	});
</script>

{#snippet chips()}
	<Badge tone={source.tone} dot live={session.running}><span class="sr-only">Data: </span>{source.text}</Badge>
	{#if markets}
		<Badge tone={markets.ai_enabled ? 'info' : 'neutral'} dot>
			{markets.ai_enabled ? `AI · ${markets.ai_model?.split('/').at(-1) ?? 'on'}` : 'AI off · keyword reader'}
		</Badge>
	{/if}
{/snippet}

<header class="border-b border-border bg-card">
	<div class="flex items-center gap-3 px-4 py-3 lg:gap-6 lg:px-6">
		<a href="./" class="shrink-0" aria-label="Lotcouncil home"><BrandMark class="size-9" /></a>
		<div class="min-w-0 flex-1">
			<h1 class="m-0 truncate text-[17px] leading-tight font-semibold sm:text-lg">
				Lotcouncil
				<span class="hidden font-normal text-muted-foreground sm:inline">· put your trading idea on trial</span>
			</h1>
			<p class="m-0 hidden truncate text-[13px] text-muted-foreground md:block">
				Fixed code rules PASS or FAIL on hourly Bitget stock-token prices. The AI only translates and explains.
			</p>
		</div>

		<div class="hidden flex-wrap items-center gap-2 md:flex" role="group" aria-label="Status">
			{@render chips()}
		</div>

		<div class="flex shrink-0 items-center gap-2">
			<button type="button" class="btn btn-secondary px-2.5 sm:px-3.5" onclick={onhow} aria-label="How it works">
				<Icon name="book" class="size-4" /><span class="hidden sm:inline">How it works</span>
			</button>
			<button
				type="button"
				class="btn btn-secondary size-10 p-0"
				aria-label="Switch between light and dark mode"
				onclick={toggleTheme}
			>
				<Icon name="moon" class="size-[18px]" />
			</button>
		</div>
	</div>
	<div class="-mt-1 flex flex-wrap gap-2 px-4 pb-2.5 md:hidden" role="group" aria-label="Status">
		{@render chips()}
	</div>
</header>
